### ISSUE TITLE
'var' parsing errors

### ISSUE THREAD

**Issue by lqd** [jlongster/es6-macros#16]
The var macro seems to cause problems with valid code.

For instance both 1)
var i;

and 2)
for (var i = 0; i < 5; ++i)
    console.log (i);
throw errors: a SyntaxError in the first case, an unexpected token in the second.

**Comment by jlongster** [comment]
You're right! I refactored that recently and didn't it test it well enough, sorry! I'm surprised the tests didn't catch that. Just published a new version to npm that works. Try it now.

**Comment by lqd** [comment]
:thumbsup: works totally fine now :)

Thanks!
