### ISSUE TITLE
[mkSyntax] You must provide an old syntax object context (or null) when creating a new syntax object.

### ISSUE THREAD

**Issue by ryanseddon** [jlongster/es6-macros#2]
When I run `make` I keep getting this error

``` bash
[mkSyntax] You must provide an old syntax object context (or null) when creating a new syntax object.
```

![screen shot 2014-02-16 at 06 05 42](https://f.cloud.github.com/assets/143402/2178320/bc1a7994-9663-11e3-975c-fec061c7a3f7.png)

**Comment by disnet** [comment]
This is happening [here](https://github.com/jlongster/es6-macros/blob/master/macros/class.sjs#L11-L14) (possibly elsewhere too). As of sweet.js v0.4.0 you must include the lexical context argument when using `makeValue`, `makeIdent`, etc..

**Comment by jlongster** [comment]
I just updated everything to work with the latest sweet.js version. A few other big changes had to be made. Should work now!

**Comment by jlongster** [comment]
Worth noting that things won't work until https://github.com/mozilla/sweet.js/pull/270 is merged. Should happen quickly though.
